FROM python:2.7
# COPY Assignment1.py /app/
# COPY Interface.py /app/
# COPY tester.py /app/
# COPY test_data.txt /app/
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir psycopg2
CMD ["tail", "-f", "/dev/null"]